### ISSUE TITLE
when i test pyflex example，it turns out some problem

### ISSUE THREAD

**Issue by yinlang832** [YunzhuLi/DPI-Net#2]
Traceback (most recent call last):
  File "test_FluidFall.py", line 3, in <module>
    import pyflex
ImportError: No module named pyflex

But pyflex should have been installed?Can you help me deal with it ？

**Comment by YunzhuLi** [comment]
This error usually occurs when the environment variables are incorrect. Have you successfully compiled the PyFleX submodule?

Also, if you are trying to run the script in a new terminal, you will have to go to the root folder of DPI-Net, and reset the environment variables using the following commands.
```
export PYFLEXROOT=${PWD}/PyFleX
export PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
export LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH
```

**Comment by yinlang832** [comment]
I test the program again,when i compile the command “git submodule update --init --recursive
" it turns out a problem：子模组 'PyFleX' (git@github.com:YunzhuLi/PyFleX.git) 未对路径 'PyFleX' 注册,but it still finish the update .Did it cause the problem？How can i deal with it ？

**Comment by yinlang832** [comment]
In fact,when i download the pyflex again,it shows some strange problem,
yin@1203:~/dpi/DPI-Net$ git submodule update --init --recursive
子模组 'PyFleX' (git@github.com:YunzhuLi/PyFleX.git) 未对路径 'PyFleX' 注册
正克隆到 'PyFleX'...
remote: Enumerating objects: 1247, done.
remote: Counting objects: 100% (1247/1247), done.
remote: Compressing objects: 100% (862/862), done.
packet_write_wait: Connection to 13.229.188.59 port 22: Broken pipe
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
fatal: 无法克隆 'git@github.com:YunzhuLi/PyFleX.git' 到子模组路径 'PyFleX'
TomorrowmI change the .githubmodule in the /home ,and then delete it,Did it cause the problem？

**Comment by yinlang832** [comment]
Besides,i download the whole program on the other documents again and the do the test .

**Comment by YunzhuLi** [comment]
I have reexamined the code, and everything works fine on my side. You will have to make sure that `.gitmodules` is not modified before you run `git submodule update --init --recursive`.

If it still does not work for you, you can clone the PyFleX repo directly in the DPI-Net root folder through
```
cd DPI-Net/
git clone https://github.com/YunzhuLi/PyFleX.git
```
and then continue on compiling PyFleX.

**Comment by yinlang832** [comment]
I download the pyflex by sudo pip3 install pyflex and then the mistakes changes,it shows that 
python3 test_FluidFall.py
Traceback (most recent call last):
  File "test_FluidFall.py", line 11, in <module>
    pyflex.init()
AttributeError: module 'pyflex' has no attribute 'init'
Do you know how can i deal with it?

**Comment by YunzhuLi** [comment]
I did not upload my `PyFleX` package to PyPI, what you are downloading using `pip install pyflex` is this [package](https://pypi.org/project/pyflex/).
