### ISSUE TITLE
Failed to run pyflex examples

### ISSUE THREAD

**Issue by xinli94** [YunzhuLi/DPI-Net#3]
Hi,

I am wondering if you could help me with this - We got a segfault when running `python test_FluidFall.py`:
```
Unable to initialize SDLCould not initialize GL extensions
Segmentation fault (core dumped)  
```

Environment settings:
+ docker container is based on: nvidia/cuda:9.1-devel-ubuntu16.04.
+ Python 3.7
+ Pytorch 1.0.0

Thanks!
Xin

**Comment by YunzhuLi** [comment]
Hi Xin,

I haven't tried to run the script inside the docker. Running PyFleX requires OpenGL to render the images, so you will need to make sure OpenGL-based applications have no problem running inside docker. However, some people seem to still have the same issue, according to [this](https://devtalk.nvidia.com/default/topic/1032752/opengl/unable-to-run-flex-despite-having-opengl-could-not-initialize-gl-extensions/).

Can you first check with your OpenGL settings? If it does not work for you, I would suggest you move outside of the docker.

Best,
Yunzhu

**Comment by xinli94** [comment]
Hi Yunzhu,

Thanks for the reply!
We have yet to find a machine that has cuda 9.1 (most of them have upgraded to CUDA 10.1 already), and that's why we resort to docker. The OpenGL should work since we are using the official NVIDIA CUDA9.1+OpenGL docker https://hub.docker.com/r/nvidia/cudagl .

Do you know if there's any way to make it work on CUDA10, or how to fix the issue that you linked?

Thanks!!

**Comment by YunzhuLi** [comment]
The core solver of the FleX simulator is not open-sourced, so if the solver is compiled using CUDA 9.1, the script may only work using the same version. I just checked the original FleX repo. They seem to have upgraded to CUDA 9.2, according to this [issue](https://github.com/NVIDIAGameWorks/FleX/issues/45).

You can try raising an issue requesting the support for CUDA 10, and we can then test to see if it resolves your issue.

Another route would be to ask them how to run their demo inside the docker. Wherever their demo works, my code should also work.

**Comment by Yusufma03** [comment]
Hi Xin, I also encountered this problem and just found a workaround. The idea is to compile the FleX inside the docker and run it outside. For the PyFleX, supposing you are using anaconda virtual environment, you have to mount your python environment folder into the docker container and compile PyFlex inside the docker. Now, export the path and you can run PyFleX outside the docker :)

**Comment by YunzhuLi** [comment]
Hi @Yusufma03, thank you so much for your solution to this issue! I've tested your approach, and it works. I've included a new [document](https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md) detailing a step-by-step instruction of how to compile PyFleX inside docker. Please let me know if you have a neater solution!

**Comment by xinli94** [comment]
Thanks all! 

I already followed the steps Yunzhu linked above, got errors: 
```
[18:00 x@server2 PyFleX] > docker run   -v WORKDIR/DPI-Net/PyFleX/:/workspace/PyFleX   -v WORKDIR/anaconda3/:/workspace/anaconda   -it yunzhuli/pyflex_16_04_cuda_9_1:latest
root@701ed62f7297:/workspace# export PATH="/workspace/anaconda/bin:$PATH"
root@701ed62f7297:/workspace# cd /workspace/PyFleX
root@701ed62f7297:/workspace/PyFleX# export PYFLEXROOT=${PWD}
root@701ed62f7297:/workspace/PyFleX# export PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
root@701ed62f7297:/workspace/PyFleX# export LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH
root@701ed62f7297:/workspace/PyFleX# cd bindings; mkdir build; cd build; cmake ..; make -j
mkdir: cannot create directory 'build': File exists
-- Found PythonInterp: /workspace/anaconda/bin/python3.7 (found version "3.7.3")
-- Found PythonLibs: python3.7m
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/PyFleX/bindings/build
Scanning dependencies of target pyflex
[  5%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/voxelize.cpp.o
[ 10%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/extrude.cpp.o
[ 15%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/pfm.cpp.o
[ 21%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/aabbtree.cpp.o
[ 31%] Building CXX object CMakeFiles/pyflex.dir/imgui.cpp.o
[ 31%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/maths.cpp.o
[ 36%] Building CXX object CMakeFiles/pyflex.dir/opengl/imguiRenderGL.cpp.o
[ 42%] Building CXX object CMakeFiles/pyflex.dir/shadersDemoContext.cpp.o
[ 47%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/core.cpp.o
[ 52%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/png.cpp.o
[ 57%] Building CXX object CMakeFiles/pyflex.dir/opengl/shader.cpp.o
[ 63%] Building CXX object CMakeFiles/pyflex.dir/pyflex.cpp.o
[ 68%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/sdf.cpp.o
[ 73%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/mesh.cpp.o
[ 78%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/tga.cpp.o
[ 89%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/perlin.cpp.o
[ 89%] Building CXX object CMakeFiles/pyflex.dir/workspace/PyFleX/core/platform.cpp.o
[ 94%] Building CXX object CMakeFiles/pyflex.dir/opengl/shadersGL.cpp.o
/workspace/PyFleX/bindings/opengl/shadersGL.cpp: In function 'GLuint LoadTexture(const char*)':
/workspace/PyFleX/bindings/opengl/shadersGL.cpp:207:16: warning: converting to non-pointer type 'GLuint {aka unsigned int}' from NULL [-Wconversion-null]
         return NULL;
                ^
/workspace/PyFleX/bindings/pyflex.cpp: In function 'int GetKeyFromGameControllerButton(SDL_GameControllerButton)':
/workspace/PyFleX/bindings/pyflex.cpp:58:9: warning: case value '17' not in enumerated type 'SDL_GameControllerButton' [-Wswitch]
         case SDL_CONTROLLER_BUTTON_RIGHT_TRIGGER:   {    return SDLK_SPACE;    }    // -- emit particles
         ^
[100%] Linking CXX shared module pyflex.cpython-37m-x86_64-linux-gnu.so
[100%] Built target pyflex
root@701ed62f7297:/workspace/PyFleX/bindings/build# cd ../..
root@701ed62f7297:/workspace/PyFleX# export PYFLEXROOT=${PWD}
root@701ed62f7297:/workspace/PyFleX# export PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
root@701ed62f7297:/workspace/PyFleX# export LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH
root@701ed62f7297:/workspace/PyFleX# cd ${PYFLEXROOT}/bindings/examples
root@701ed62f7297:/workspace/PyFleX/bindings/examples# python test_FluidFall.py
Unable to initialize SDLCould not initialize GL extensions
Segmentation fault (core dumped)
```

We will try this again on a local machine instead of remote servers.

Thanks!
Xin

**Comment by xinli94** [comment]
It works on my local machine!

Cheers!

Xin

**Comment by blue-rabbitt** [comment]
Hi, I've followed the new document (https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md) and there seems to be no problem compiling PyFlex in the docker environment but I'm still getting the segmentation fault when running python test_FluidFall.py with the message 'Unable to initialize SDLCould not initialize GL extensions'.
My settings are Ubuntu 16.04, Python 3.7, Pytorch 1.4.0.
Thanks!
