### ISSUE TITLE
Is it possible to run this on CPU?

### ISSUE THREAD

**Issue by NagabhushanSN95** [YunzhuLi/DPI-Net#5]
Hi, installation guide for PyFlex explains installing on a GPU machine. Is it possible to install and run this (evaluation only) on a CPU?

**Comment by YunzhuLi** [comment]
To launch PyFleX, the current setup requires CUDA support.

You may take a look at the following repo that we just released for training and evaluating the particle dynamics networks, which is an upgrade of DPI-Net that the evaluation can directly run on CPU, where we replaced PyFleX with VisPy for visualizing the results.
[https://github.com/YunzhuLi/VGPL-Dynamics-Prior](https://github.com/YunzhuLi/VGPL-Dynamics-Prior)

This section discussed the difference between DPI-Net and VGPL-Dynamics-Prior.
[https://github.com/YunzhuLi/VGPL-Dynamics-Prior#difference-between-this-repo-and-dpi-net](https://github.com/YunzhuLi/VGPL-Dynamics-Prior#difference-between-this-repo-and-dpi-net)

**Comment by NagabhushanSN95** [comment]
Oh great! Thanks. I'll check it out
