### ISSUE TITLE
Question about running enviroment

### ISSUE THREAD

**Issue by qingfengtommy** [YunzhuLi/DPI-Net#7]
Dear Yunzhi Li,

I appreciate your generosity in sharing the source code.

I am currently endeavoring to replicate the original datasets on a remote headless server running Linux 18.04 with Nvidia Driver, and this setup lacks physical monitors. It appears that OpenGL doesn't work in the absence of a physical screen.

Could you kindly provide more information about your server environment? Specifically, does it include a physical monitor? I am eager to determine whether it is feasible to reproduce the dataset within a screenless environment.

Best,
Tommy

**Comment by YunzhuLi** [comment]
@WangYixuan12 has a headless version of PyFleX. Yixuan, would you mind helping @qingfengtommy with this issue?

**Comment by WangYixuan12** [comment]
Sure! Hi @qingfengtommy, you can install the headless version of PyFleX from [this repo](https://github.com/WangYixuan12/dyn-res-pile-manip), and you can specify whether it is a headless version by passing argument into pyflex.init()

**Comment by qingfengtommy** [comment]
Thank you so mucn for your help! @YunzhuLi  and @WangYixuan12. Now I can initialize pyflex successfully. However, when I tried to run python test_RigidFall.py, I got the incompatible function arguements.

```python test_RigidFall.py 
Compute Device: NVIDIA A100 80GB PCIe

Scene Upper: [-0.01 -0.01 -0.01]
Scene Lower: [0.6959432  0.27906132 0.41      ]
Traceback (most recent call last):
  File "/home/user/exp/DPI-Net/PyFleX/bindings/examples/test_RigidFall.py", line 40, in <module>
    pyflex.step(capture=1, path=os.path.join(des_dir, 'render_%d.tga' % i))
TypeError: step(): incompatible function arguments. The following argument types are supported:
    1. (update_params: numpy.ndarray[numpy.float32] = None, draw_planes: int = 1, draw_objects: int = 1, draw_shadow: int = 1, render_depth: bool = 0) -> None

Invoked with: kwargs: capture=1, path='test_RigidFall/render_0.tga
```
I also got a similiar error when running bash ./scripts/eval_FluidFall.sh
```
Step 90 / 120
Step 100 / 120
Step 110 / 120
Traceback (most recent call last):
  File "/home/user/exp/DPI-Net/eval.py", line 436, in <module>
    pyflex.render(capture=1, path=os.path.join(des_dir, 'gt_%d.tga' % step))
TypeError: render(): incompatible function arguments. The following argument types are supported:
    1. (draw_planes: int = 1, draw_objects: int = 1, draw_shadow: int = 1, render_depth: bool = 0) -> numpy.ndarray[numpy.float32]

Invoked with: kwargs: capture=1, path='dump_FluidFall/eval_FluidFall/rollout_0/gt_0.tga'
```
Could you please give any suggestions?
In addition, would it be possible for you to provide a short documentation for the headless version of PyFleX in the future?
That would be more convenient for debugging. :)

**Comment by WangYixuan12** [comment]
I currently have no official doc. But you can find how python APIs are defined [here](https://github.com/WangYixuan12/dyn-res-pile-manip/blob/500cf7c1d9067202acc7b6f56d4f1f26a8005d79/PyFleX/bindings/pyflex.cpp#L3797). Corresponding C++ functions are defined in `pyflex.cpp` as well.

Currently, running `test_RigidFall.py` is not supported by PyFleX of this [repo](https://github.com/WangYixuan12/dyn-res-pile-manip). If you want to have a PyFleX that supports both render in DPI-Net and headless rendering, you might need to change upon the PyFleX within DPI-Net repo. You could refer to softgym's PyFleX to see how the headless rendering is supported.

**Comment by qingfengtommy** [comment]
Got it! Thank you so much for your help!
